name: Build ReSukiSU Kernel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
    - cron: '0 12 * * 5'
    - cron: '0 12 * * 3'

jobs:
  build:
    name: Compile Kernel
    runs-on: ubuntu-24.04

    steps:
      - name: Configure Fast APT Mirror
        uses: vegardit/fast-apt-mirror.sh@v1

      - name: Make Build Environment
        timeout-minutes: 10
        run: |
          sudo apt-get update
          sudo apt-get install -y kmod cpio binutils cmake binutils-aarch64-linux-gnu git wget pahole automake flex lzop bison gperf build-essential zip curl zlib1g-dev libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip dwarves device-tree-compiler python3 ccache git-lfs gnupg imagemagick libelf-dev libncurses5-dev libsdl1.2-dev gpart fuse2fs e2fsck-static icu-doc rsync adb fastboot libstdc++6 python-is-python3 gcc-aarch64-linux-gnu 
          mkdir -p kernel
      - name: Checkout Kernel Source
        uses: actions/checkout@v6
        with:
          repository: miaizhe/realme_Q3pro_AndroidT_kernel-source
          path: kernel/msm-4.19
          fetch-depth: 1

      - name: Checkout Modules Source
        uses: actions/checkout@v6
        with:
          repository: realme-kernel-opensource/realme_Q3pro_AndroidT_vendor-source
          path: temp_modules
          ref: master

      - name: Prepare Compiler
        run: |
          mkdir -p compiler
          cd compiler
          
          curl -fL "https://github.com/Rancemxn/android_kernel_oppo_sm7325/releases/download/BuildTool/linux-x86-refs_heads_llvm-r383902b-clang-r383902.tar.gz" -o clang-r383902.tar.gz --connect-timeout 30 --retry 5 --retry-delay 5
          mkdir -p clang-bin
          tar -xzf clang-r383902.tar.gz -C clang-bin
          rm clang-r383902.tar.gz
      - name: Handle Dependencies
        run: |
          mv temp_modules/vendor ./vendor
          rm -rf temp_modules
      - name: Set Release Info & Custom Version
        run: |
          BUILD_DATE=$(date +%Y%m%d)
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

      - name: rekernel
        run: |
          cd kernel/msm-4.19
          curl -LSs "https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Rekernel/rekernel_patches.sh" -o rekernel_patches.sh
          chmod +x rekernel_patches.sh
          bash rekernel_patches.sh
          mkdir -p drivers/rekernel
          curl https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Rekernel/rekernel_extra.patch -o rekernel_extra.patch
          patch -p1 < rekernel_extra.patch || true
          
      - name: Compile Kernel
        run: |
          export PATH="$(pwd)/compiler/clang-bin/bin:$PATH"
          export CROSS_COMPILE="aarch64-linux-android-"
          export CROSS_COMPILE_ARM32="arm-linux-androideabi-"
          export CLANG_TRIPLE="aarch64-linux-gnu-"
          export CLANG_PATH="$(pwd)/compiler/clang-bin/bin"
          export ARCH="arm64"
          export SUBARCH="arm64"
          cd kernel/msm-4.19
          curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash
          curl -LSs "https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/mainline/Patches/syscall_hook_patches.sh" -o syscall_hook_patches.sh
          chmod +x syscall_hook_patches.sh
          bash syscall_hook_patches.sh
          make O=out CC="clang" LLVM=1 k6885v1_64_defconfig
          ./scripts/config --file out/.config \
            -d CONFIG_KSU_TRACEPOINT_HOOK \
            -e CONFIG_KSU_MANUAL_HOOK
          make O=out CC="clang" LLVM=1 -j$(nproc)
      - name: Package with AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git AnyKernel3
          sed -i '584s|ui_print " " "Done!";|ui_print " "; ui_print "感谢支持芜夕wuxi内核，刷入完成！"; ui_print "祝你玩的愉快！";|' AnyKernel3/META-INF/com/google/android/update-binary
          
          cp kernel/msm-4.19/out/arch/arm64/boot/Image AnyKernel3/
          mkdir -p AnyKernel3/modules/vendor/lib/modules
          find kernel/msm-4.19/out/ -name "*.ko" -exec cp {} AnyKernel3/modules/vendor/lib/modules/ \;
          
          cd AnyKernel3
          rm anykernel.sh
          wget https://github.com/miaizhe/Kernel_oppo_sm7325_Reno10/releases/download/boot/anykernel.sh
          zip -r9 ../ReSukiSU-q3pro-${{ env.BUILD_DATE }}.zip * -x .git* README.md *placeholder

      - name: Upload Flashable Kernel
        uses: actions/upload-artifact@v6
        with:
          name: ReSukiSU_Reno10_Flashable
          path: ReSukiSU-Reno10-Kernel.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_DATE }}
          name: KernelSU Kernel for q3pro (${{ env.BUILD_DATE }})
          body: |
            - 编译日期: ${{ env.BUILD_DATE }}
            - 核心版本: 4.19
            - 包含功能: ReSukiSU
            - 欢迎刷入芜夕wuxi的内核！祝你玩的愉快！
            - 文件：分为带SuSFS的和不带SukiSU的，zip为ak3包，img文件为打包好的镜像，Docker为带Docker的
          files: |
              ReSukiSU-q3pro-${{ env.BUILD_DATE }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
